// <auto-generated />
namespace Mansour_NDIAYE.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class PremierMigration : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(PremierMigration));
        
        string IMigrationMetadata.Id
        {
            get { return "202501131402424_Premier-Migration"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
